
language: rust
rust:
  - nightly

install:
  - echo 'deb http://download.opensuse.org/repositories/home:/strik/Debian_9.0/ /' > /etc/apt/sources.list.d/home:strik.list
  - apt-get update
  - apt-get install cc65
  - cargo build --verbose

