
language: rust
rust:
  - nightly
cache:
  cargo: true
  directories:
    - integration/.cc65

before_install:
  - sudo apt-get install libegl1-mesa-dev
  - sudo apt-get install libgles2-mesa-dev
  - sudo apt-get install libsdl2-dev

